[pytest]
# Настройки pytest
addopts = -v --tb=short --alluredir=allure_results

# Где искать тесты
testpaths = tests

# Паттерн для файлов с тестами
python_files = test_*.py

# Паттерн для классов с тестами
python_classes = Test*

# Паттерн для функций тестов
python_functions = test_*

# Маркеры
markers =
    faq: тесты для раздела FAQ
    order: тесты для заказа самоката
    logos: тесты для логотипов
